const p = [
  'Glasgow Hammer',
  'Calamity Rescue',
  'Leuchtturm Hans',
  'Hazard Kraken',
  'Duster Catapult',
  'Sagarmāthā 1',
  'Sword of Kathmandu',
  'Chinde Duk',
  'Divine Ascendant ',
  'Buzkashi Mare',
  'U-wetatso ',
  'Tsa-huro',
  'Mosadatsi',
  'Sha-ea',
  'Disintu',
  'Legion Red',
  'Vicious Whisper',
  'King Bull',
  'Ultimate Gun-Head',
  'Astro Nergal',
  'Guardian Preserver',
  'Electro Blossom',
  'Beautiful Amavasya',
  'Shadow Virago',
  'Lotus of Delight',
  'Saxophone Blue',
  'Melodious Mistake',
  'Queen\'s Gambit',
  'Weeping Willow',
  'Radiant Memento',
  'Self Entitled',
  'Listen Here You',
  'Cry Power',
  'Beyond the Hour',
  'Lacking in Culture if Not Grace',
  'White Dwarf',
  'Dream Spirit',
  'Tactic Vulcan',
  'Gorgon Manticore',
  'Super Noise-Man',
  'Alpha Mobile',
  'Striker Blitz',
  'Wing Harrier',
  'Echo 27A',
  'Echo 28A',
  'Immortal Kamehameha',
  'Raddon the Destroyer',
  'Chariot Bandido',
  'Mephist Zero',
  'Fang Favorite',
  'Ba\'al Buster',
  'Cocytus Tributary',
  'Scylla Snacktime',
  'Error: Divide By Zero',
  'An Exception Has Occurred',
  'Landing Gear Damaged',
  'Could Not Locate Name',
  'Core Dump',
  'Siege ',
  'Titan Ant Cordyceps',
  'Mighty Tortuga',
  'Atomic Sarcosuchus',
  'Mother Anemone ',
  'Rustbucket',
  'Longhaul',
  'Rollcage',
  'Christine',
  'Octoplasm V',
  'Typhoon Pioneer',
  'Caesar Dragoon',
  '18 Karat Simurgh',
  'Unit-069',
  'Drift Fighter Z',
  'Golden Heel',
  'Jade Hornet Master',
  'Super God Apex',
  'Hansel/Gretel Duo-Type',
  'Panzer Bluebeard',
  'Frost Banshee',
  'Princess Midnight',
  'Strain Sigma',
  'DNA Fistfight',
  'Hybrid X51',
  'Evolution Terminus',
  'Homo Navis'
];

const players = {
  'Glasgow Hammer': {stability: 5, accuracy: 3, speed: 5, jump: 2},
  'Calamity Rescue': {stability: 2, accuracy: 2, speed: 3, jump: 1},
  'Leuchtturm Hans': {stability: 4, accuracy: 3, speed: 3, jump: 5},
  'Hazard Kraken': {stability: 5, accuracy: 1, speed: 4, jump: 5},
  'Duster Catapult': {stability: 2, accuracy: 1, speed: 4, jump: 4},
  'SagarmÄthÄ 1': {stability: 4, accuracy: 4, speed: 3, jump: 1},
  'Sword of Kathmandu': {stability: 3, accuracy: 4, speed: 1, jump: 3},
  'Chinde Duk': {stability: 2, accuracy: 5, speed: 1, jump: 4},
  'Divine Ascendant': {stability: 4, accuracy: 5, speed: 3, jump: 4},
  'Buzkashi Mare': {stability: 2, accuracy: 3, speed: 4, jump: 3},
  'U-wetatso': {stability: 2, accuracy: 2, speed: 3, jump: 1},
  'Tsa-huro': {stability: 2, accuracy: 3, speed: 3, jump: 4},
  'Mosadatsi': {stability: 4, accuracy: 5, speed: 1, jump: 5},
  'Sha-ea': {stability: 5, accuracy: 3, speed: 3, jump: 1},
  'Disintu': {stability: 2, accuracy: 1, speed: 1, jump: 1},
  'Legion Red': {stability: 3, accuracy: 3, speed: 3, jump: 3},
  'Vicious Whisper': {stability: 1, accuracy: 1, speed: 3, jump: 5},
  'King Bull': {stability: 3, accuracy: 1, speed: 1, jump: 1},
  'Ultimate Gun-Head': {stability: 2, accuracy: 2, speed: 4, jump: 3},
  'Astro Nergal': {stability: 4, accuracy: 3, speed: 5, jump: 4},
  'Guardian Preserver': {stability: 1, accuracy: 5, speed: 5, jump: 3},
  'Electro Blossom': {stability: 2, accuracy: 4, speed: 3, jump: 4},
  'Beautiful Amavasya': {stability: 3, accuracy: 2, speed: 2, jump: 4},
  'Shadow Virago': {stability: 2, accuracy: 2, speed: 4, jump: 1},
  'Lotus of Delight': {stability: 2, accuracy: 1, speed: 2, jump: 5},
  'Saxophone Blue': {stability: 3, accuracy: 3, speed: 4, jump: 2},
  'Melodious Mistake': {stability: 2, accuracy: 5, speed: 3, jump: 5},
  'Queen\'s Gambit': {stability: 1, accuracy: 1, speed: 1, jump: 3},
  'Weeping Willow': {stability: 5, accuracy: 3, speed: 5, jump: 3},
  'Radiant Memento': {stability: 3, accuracy: 5, speed: 5, jump: 1},
  'Self Entitled': {stability: 5, accuracy: 1, speed: 1, jump: 1},
  'Listen Here You': {stability: 1, accuracy: 3, speed: 2, jump: 4},
  'Cry Power': {stability: 1, accuracy: 4, speed: 5, jump: 1},
  'Beyond the Hour': {stability: 5, accuracy: 5, speed: 4, jump: 2},
  'Lacking in Culture if Not Grace': {stability: 3, accuracy: 3, speed: 5, jump: 4},
  'White Dwarf': {stability: 5, accuracy: 4, speed: 3, jump: 5},
  'Dream Spirit': {stability: 3, accuracy: 3, speed: 4, jump: 5},
  'Tactic Vulcan': {stability: 3, accuracy: 2, speed: 4, jump: 3},
  'Gorgon Manticore': {stability: 4, accuracy: 2, speed: 3, jump: 5},
  'Super Noise-Man': {stability: 2, accuracy: 4, speed: 1, jump: 2},
  'Alpha Mobile': {stability: 4, accuracy: 2, speed: 1, jump: 5},
  'Striker Blitz': {stability: 3, accuracy: 5, speed: 1, jump: 3},
  'Wing Harrier': {stability: 1, accuracy: 1, speed: 1, jump: 2},
  'Echo 27A': {stability: 2, accuracy: 3, speed: 1, jump: 5},
  'Echo 28A': {stability: 2, accuracy: 4, speed: 4, jump: 4},
  'Immortal Kamehameha': {stability: 3, accuracy: 2, speed: 5, jump: 4},
  'Raddon the Destroyer': {stability: 4, accuracy: 1, speed: 3, jump: 3},
  'Chariot Bandido': {stability: 2, accuracy: 4, speed: 4, jump: 3},
  'Mephist Zero': {stability: 4, accuracy: 2, speed: 1, jump: 3},
  'Fang Favorite': {stability: 4, accuracy: 3, speed: 3, jump: 5},
  'Ba\'al Buster': {stability: 2, accuracy: 5, speed: 3, jump: 1},
  'Cocytus Tributary': {stability: 1, accuracy: 2, speed: 2, jump: 4},
  'Scylla Snacktime': {stability: 2, accuracy: 3, speed: 4, jump: 3},
  'Error: Divide By Zero': {stability: 5, accuracy: 1, speed: 3, jump: 4},
  'An Exception Has Occurred': {stability: 2, accuracy: 2, speed: 4, jump: 4},
  'Landing Gear Damaged': {stability: 3, accuracy: 5, speed: 5, jump: 2},
  'Could Not Locate Name': {stability: 5, accuracy: 5, speed: 4, jump: 4},
  'Core Dump': {stability: 4, accuracy: 4, speed: 3, jump: 3},
  'Siege': {stability: 5, accuracy: 4, speed: 1, jump: 3},
  'Titan Ant Cordyceps': {stability: 5, accuracy: 1, speed: 3, jump: 5},
  'Mighty Tortuga': {stability: 5, accuracy: 2, speed: 1, jump: 4},
  'Atomic Sarcosuchus': {stability: 4, accuracy: 3, speed: 1, jump: 2},
  'Mother Anemone': {stability: 3, accuracy: 4, speed: 5, jump: 2},
  'Rustbucket': {stability: 1, accuracy: 5, speed: 3, jump: 1},
  'Longhaul': {stability: 1, accuracy: 5, speed: 2, jump: 3},
  'Rollcage': {stability: 3, accuracy: 2, speed: 4, jump: 2},
  'Christine': {stability: 3, accuracy: 2, speed: 1, jump: 2},
  'Octoplasm V': {stability: 3, accuracy: 1, speed: 5, jump: 1},
  'Typhoon Pioneer': {stability: 1, accuracy: 3, speed: 4, jump: 3},
  'Caesar Dragoon': {stability: 1, accuracy: 4, speed: 4, jump: 1},
  '18 Karat Simurgh': {stability: 2, accuracy: 4, speed: 3, jump: 2},
  'Unit-069': {stability: 5, accuracy: 1, speed: 2, jump: 1},
  'Drift Fighter Z': {stability: 4, accuracy: 4, speed: 3, jump: 2},
  'Golden Heel': {stability: 5, accuracy: 4, speed: 2, jump: 2},
  'Jade Hornet Master': {stability: 2, accuracy: 2, speed: 2, jump: 3},
  'Super God Apex': {stability: 3, accuracy: 2, speed: 4, jump: 4},
  'Hansel/Gretel Duo-Type': {stability: 2, accuracy: 3, speed: 1, jump: 4},
  'Panzer Bluebeard': {stability: 5, accuracy: 3, speed: 1, jump: 3},
  'Frost Banshee': {stability: 2, accuracy: 5, speed: 1, jump: 2},
  'Princess Midnight': {stability: 2, accuracy: 4, speed: 5, jump: 3},
  'Strain Sigma': {stability: 5, accuracy: 1, speed: 4, jump: 1},
  'DNA Fistfight': {stability: 1, accuracy: 4, speed: 5, jump: 1},
  'Hybrid X51': {stability: 2, accuracy: 4, speed: 4, jump: 2},
  'Evolution Terminus': {stability: 4, accuracy: 2, speed: 5, jump: 2},
  'Homo Navis': {stability: 5, accuracy: 1, speed: 4, jump: 5},
};

